---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: core-applications
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/apps
    repoURL: https://github.com/camptocamp/camptocamp-devops-stack.git
    targetRevision: v0.5.0
    helm:
      values: |
        baseDomain: {{ .Values.baseDomain }}
        spec:
          source:
            repoURL: https://github.com/camptocamp/camptocamp-devops-stack.git
            targetRevision: v0.5.0
          destination:
            server: {{ .Values.spec.destination.server }}
        apps:
          apps:
            enabled: false
          demo-app:
            enabled: false
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
